server:
   port: 8089
spring:
   application:  
      name: gatewayService
      
eureka:      
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost 

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    regService:
      path: /registration/**
      service-id: regService
      strip-prefix: true
    documentVallidationService:
      path: /vallidation/**
      service-id: documentVallidationService
      strip-prefix: true
    docUploadService:
      path: /upload/**
      service-id: docUploadService
      strip-prefix: true
 
         
